## IMPORTING DATASET

In [1]:
import pandas as pd
import numpy as np


## LOADING DATASET

In [2]:
dataset=pd.read_csv('Train.csv')


In [3]:
dataset.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

## GETTING X AND y VALUES FROM THE DATASET

In [5]:
X=dataset.iloc[:,:-1].values
ones=np.ones([X.shape[0],1])      #vector with number of rows equal to number of rows equal to X 
X=np.concatenate((ones,X),axis=1) #This concatenation helps us deal with the constant term in the parameter matrix and 
                                  #our gradient descent is able to perform its action using a single equation

In [6]:
print(X)
print(ones)

[[ 1.          0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [ 1.         -0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 1.          0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.          1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [ 1.         -1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [ 1.         -1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [8]:
y=dataset.iloc[:,-1:].values
print(y)

[[ -82.15466656]
 [ -48.89796018]
 [  77.2703707 ]
 ...
 [-107.51050797]
 [ -47.34155781]
 [-115.93900296]]


## SETTING HYPERPARAMETERS

In [12]:
theta=np.zeros([1,X.shape[1]])      #randomly initiliazed the values of coefficients to 0
#print(theta)             
alpha=0.01                #learning rate
iters=1000                #number of times gradient descent works

## COST FUNCTION

In [13]:
def computeCost(X,y,theta):
    toBeSummed=np.power(((X@theta.T)-y),2)
    return np.sum(toBeSummed)/(2*len(X))

## CURRENT VALUE OF COST FUNCTION

In [14]:
print(computeCost(X,y,theta))    #we have to minimize this value using gradient descent

6128.065207016448


## GRADIENT DESCENT FUNCTION

In [17]:
def gradientDescent(X,y,theta,iters,alpha):
    cost=np.zeros(iters)
    for i in range(iters):
        theta=theta-(alpha/len(X))*np.sum((X*(X@theta.T-y)),axis=0)     
        cost[i]=computeCost(X,y,theta)
    return theta,cost


## MODEL IN ACTION

In [18]:
g,cost=gradientDescent(X,y,theta,iters,alpha)
print(g)

[[ 4.98825521 29.67987527 92.65908015  8.27756078 44.76510038  2.51769725]]


In [19]:
finalCost=computeCost(X,y,g)
print(finalCost)

207.77667691150938


In [20]:
print(cost)           #as we can see the cost is decresing and hence checking the correctness of the code 
                      #and the wonders of gradient descent

[6006.89247246 5888.2120594  5771.97246864 5658.12326966 5546.61507839
 5437.39953537 5330.42928441 5225.65795172 5123.04012544 5022.53133558
 4924.08803445 4827.66757743 4733.22820415 4640.72902013 4550.12997872
 4461.39186344 4374.47627075 4289.34559308 4205.96300228 4124.29243343
 4044.29856892 3965.94682293 3889.20332616 3814.034911   3740.40909687
 3668.29407595 3597.6586992  3528.47246265 3460.70549398 3394.3285394
 3329.31295078 3265.63067306 3203.25423192 3142.15672174 3082.31179372
 3023.69364435 2966.27700407 2910.03712619 2854.94977599 2800.99122011
 2748.13821613 2696.36800237 2645.6582879  2595.98724278 2547.33348846
 2499.67608844 2452.99453905 2407.26876051 2362.4790881  2318.60626352
 2275.63142654 2233.53610663 2192.30221496 2151.91203642 2112.34822191
 2073.59378071 2035.63207306 1998.44680289 1962.02201067 1926.34206644
 1891.39166299 1857.15580913 1823.61982317 1790.76932649 1758.59023726
 1727.06876428 1696.19140097 1665.94491945 1636.31636478 1607.2930493
 1578.86